import { Food } from "./app/shared/models/Food";
import { Tag } from "./app/shared/models/Tag";
export const sample_foods:Food[]=
[
    {   id:'1',
        name:'chicken soup',
        price: 11,
        cookTime:'40-50',
        favourite:false,
        origins:['india','asia'],
        stars:3.0,
        imageUrl:'assets/food-1.jpeg',
        tags:['Slowfood','Soup']
    },
    {
        id:'2',
        name:'vegetable pizza',
        price: 9,
        cookTime:'40-50',
        favourite:false,
        origins:['italy'],
        stars:4.0,
        imageUrl:'assets/food-2.jpeg',
        tags:['FastFood','Pizza']
    },
    {   id:'3',
        name:'pasta',
        price: 11,
        cookTime:'20-30',
        favourite:false,
        origins:['italy'],
        stars:3.5,
        imageUrl:'assets/food-3.jpeg',
        tags:['FastFood','noodles','Soup']
    },
    {   id:'4',
        name:'paneer tikka',
        price: 17,
        cookTime:'30-40',
        favourite:true,
        origins:['india'],
        stars:4.5,
        imageUrl:'assets/food-4.jpeg',
        tags:['Slowfood','Soup']
    },
    {   id:'5',
        name:'gobi manchurian',
        price: 11,
        cookTime:'10-20',
        favourite:false,
        origins:['china','asia'],
        stars:3.0,
        imageUrl:'assets/food-5.jpeg',
        tags:['FastFood']
    },
    {   id:'6',
        name:'fried rice',
        price: 16,
        cookTime:'10-20',
        favourite:true,
        origins:['india','asia','china','japan'],
        stars:3.0,
        imageUrl:'assets/food-6.jpeg',
        tags:['FastFood','rice','Lunch','Fry']
    },
    {   id:'7',
        name:'masala dosa',
        price: 13,
        cookTime:'10-20',
        favourite:true,
        origins:['india'],
        stars:4.0,
        imageUrl:'assets/food-7.jpeg',
        tags:['FastFood','north indian','Fry']
    },
    {   id:'8',
        name:'kolhapuri misal',
        price: 10,
        cookTime:'20-30',
        favourite:true,
        origins:['india'],
        stars:4.0,
        imageUrl:'assets/food-8.jpeg',
        tags:['FastFood','Spicy']
    },
    {   id:'9',
        name:'ramen noodles',
        price: 18,
        cookTime:'40-50',
        favourite:false,
        origins:['japanese','asia'],
        stars:3.5,
        imageUrl:'assets/food-9.jpeg',
        tags:['slowfood','Soup','noodles']
    },
    {   id:'10',
        name:'punjabi thali',
        price: 17,
        cookTime:'40-50',
        favourite:false,
        origins:['india','asia'],
        stars:3.0,
        imageUrl:'assets/food-10.jpeg',
        tags:['Slowfood','Lunch']
    },
    {   id:'11',
        name:'fasting khichdi',
        price: 8,
        cookTime:'20-30',
        favourite:false,
        origins:['india'],
        stars:3.0,
        imageUrl:'assets/food-11.jpeg',
        tags:['Slowfood','fasting food']
    },
    {   id:'12',
        name:'chole bhature',
        price: 12,
        cookTime:'10-20',
        favourite:true,
        origins:['india','asia'],
        stars:3.0,
        imageUrl:'assets/food-12.jpeg',
        tags:['FastFood','Lunch']
    },
]

export const sample_tags:Tag[]=
[
    {name:'All', count:6},
    {name:'FastFood', count:7},
    {name:'Pizza', count:1},
    {name:'Lunch', count:3},
    {name:'Soup', count:3},
    {name:'Fry', count:2},
    {name:'SlowFood', count:5},
]